pipeline {

//agent { label "windows" } 
agent any
options { disableConcurrentBuilds() }
//tools { maven 'MVN' } 
stages {

   stage('APICall') {
      steps {
         bat label: 'Retrieve Product from API', returnStdout: true, script: '"C:\\Program Files\\SmartBear\\ReadyAPI-2.6.0\\bin\\testrunner.bat" -sWebStoreTestSuite -cBareGetOrderRequest -r -a -j -f${WORKSPACE} "-RJUnit-Style HTML Report" -FXML "-EDefault environment" -tC:\\Users\\dermot.canniffe\\soapui-settings.xml "C:\\Users\\dermot.canniffe\\OneDrive - SmartBear Software, Inc\\ReadyAPI Projects\\Project-2-readyapi-project"'
      }
   }
   stage('TestComplete') {
    steps {
        // One or more steps need to be included within the steps block.
        testcompletetest generateMHT: true, launchType: 'lcKdt', project: 'TC_Demonstration', suite: 'C:\\Users\\dermot.canniffe\\OneDrive - SmartBear Software, Inc\\TestComplete 14 Projects\\LatestDemoProject\\DemoProject2.pjs', test: 'PurchaseWithBackendValidation', useTCService: true, userName: 'AD\\dermot.canniffe', userPassword: 'C97h21a596'
        }
    }
   stage('Results') {
      steps {
      junit '**/target/surefire-reports/TEST-*.xml'
      archive 'target/*.jar'
   }
    }
}
}
